# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-30 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uicon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
